import { theme } from "antd";

export const antTheme = {
  algorithm: theme.defaultAlgorithm,
  token: {
    fontFamily: '"Rubik", system-ui, -apple-system, "Segoe UI", sans-serif',
    colorText: "#51463B",
    colorTextSecondary: "#6F6153",
    colorPrimary: "#225555",
    colorSuccess: "#6B8A5D",
    colorWarning: "#A06B2A",
    colorError: "#DA8787",
    colorInfo: "#9CD3D3",
    colorBorder: "#225555",
    colorBorderSecondary: "rgba(34, 85, 85, 0.22)",
    colorBgBase: "#FAFAEE",
    colorBgLayout: "#F6F0E4",
    colorBgContainer: "#FFFDF6",
    colorFillAlter: "#EFE6D8",
    lineWidth: 2,
    lineWidthBold: 2,
    borderRadius: 18,
    borderRadiusLG: 18,
    borderRadiusSM: 18,
    controlHeightSM: 28,
    controlHeight: 36,
    boxShadow: "none",
    boxShadowSecondary: "0 18px 42px rgba(81, 70, 59, 0.14)",
    motionDurationFast: "0.12s",
    motionDurationMid: "0.18s",
  },
  components: {
    Layout: {
      bodyBg: "#F6F0E4",
      headerBg: "#FFFDF6",
      siderBg: "#EFE6D8",
    },
    Card: {
      colorBgContainer: "#E5D4C3",
      borderRadiusLG: 18,
      boxShadowTertiary: "none",
      headerBg: "#EFE6D8",
      bodyPadding: 12,
    },
    Button: {
      borderRadius: 18,
      controlHeightLG: 32,
      controlHeightSM: 24,
      fontWeight: 500,
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
    },
    Input: {
      borderRadius: 18,
      activeBorderColor: "#225555",
      hoverBorderColor: "#225555",
      activeShadow: "0 0 0 3px rgba(34, 85, 85, 0.12)",
    },
    Table: {
      borderColor: "rgba(34, 85, 85, 0.22)",
      headerBg: "#EFE6D8",
      rowHoverBg: "#F5EFE2",
      headerSplitColor: "transparent",
      cellPaddingBlock: 6,
      cellPaddingInline: 8,
    },
    Modal: {
      boxShadow: "none",
    },
    Tooltip: {
      borderRadius: 6,
    },
    Segmented: {
      itemActiveBg: "#FFFDF6",
      itemHoverBg: "#E5DACE",
      itemSelectedBg: "#CBC4AF",
      trackBg: "#EFE6D8",
      trackPadding: 2,
      borderRadius: 18,
    },
    Tag: {
      borderRadiusSM: 18,
      defaultBg: "#EFE6D8",
      defaultColor: "#51463B",
    },
    Checkbox: {
      colorPrimary: "#225555",
      colorPrimaryHover: "#163D3D",
    },
    Select: {
      optionSelectedBg: "#CBC4AF",
    },
  },
};
