import { theme } from "antd";

export const antTheme = {
  algorithm: theme.defaultAlgorithm,
  token: {
    fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    colorPrimary: "#0060df",
    colorSuccess: "#1a7f37",
    colorWarning: "#b56d00",
    colorError: "#cf222e",
    colorInfo: "#0060df",
    colorBgBase: "#ffffff",
    colorBgLayout: "#f3f3f3",
    colorBgContainer: "#ffffff",
    colorText: "#202020",
    colorTextSecondary: "#595959",
    colorBorder: "#d1d1d1",
    colorBorderSecondary: "#e1e1e1",
    borderRadius: 4,
    borderRadiusLG: 6,
    borderRadiusSM: 2,
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    boxShadowSecondary: "0 4px 12px rgba(0, 0, 0, 0.08)",
    lineWidth: 1,
    motionDurationFast: "0s",
    motionDurationMid: "0s",
    controlHeight: 28,
  },
  components: {
    Layout: {
      bodyBg: "#f3f3f3",
      headerBg: "#ffffff",
      siderBg: "#fafafa",
    },
    Card: {
      borderRadiusLG: 6,
      boxShadowTertiary: "none",
      headerBg: "#fafafa",
      bodyPadding: 12,
    },
    Button: {
      borderRadius: 4,
      controlHeightLG: 32,
      controlHeightSM: 24,
      fontWeight: 500,
      primaryShadow: "none",
      defaultShadow: "none",
    },
    Input: {
      borderRadius: 4,
      activeBorderColor: "#0060df",
      hoverBorderColor: "#0060df",
    },
    Table: {
      borderColor: "#d1d1d1",
      headerBg: "#fafafa",
      rowHoverBg: "#f0f4f8",
      headerSplitColor: "transparent",
      cellPaddingBlock: 6,
      cellPaddingInline: 8,
    },
    Segmented: {
      itemActiveBg: "#ffffff",
      itemHoverBg: "#e1e1e1",
      itemSelectedBg: "#ffffff",
      trackBg: "#f3f3f3",
      trackPadding: 2,
      borderRadius: 4,
    },
    Tag: {
      borderRadiusSM: 2,
      defaultBg: "#f3f3f3",
      defaultColor: "#202020",
    },
  },
};